PrimeFaces.locales['pt_BR'] = {
    closeText : 'Fechar',
    prevText : 'Anterior',
    nextText : 'Próximo',
    currentText : 'Começo',
    monthNames : [ 'Janeiro', 'Fevereiro', 'Mar\u00e7o', 'Abril', 'Maio', 'Junho','Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro' ],
    monthNamesShort : [ 'Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago','Set', 'Out', 'Nov', 'Des' ],
    dayNames : [ 'Domingo', 'Segunda', 'Ter\u00e7a', 'Quarta', 'Quinta', 'Sexta','S\u00e1bado' ],
    dayNamesShort : [ 'Dom', 'Seg', 'Ter', 'Quar', 'Quin', 'Sex', 'S\u00e1b' ],
    dayNamesMin : [ 'D', 'S', 'T', 'Q', 'Q', 'S', 'S' ],
    weekHeader : 'Semana',
    firstDay : 1,
    isRTL : false,
    showMonthAfterYear : false,
    yearSuffix : '',
    timeOnlyTitle : 'Só Horas',
    timeText : 'Tempo',
    hourText : 'Hora',
    minuteText : 'Minuto',
    secondText : 'Segundo',
    ampm : false,
    month : 'Mês',
    week : 'Semana',
    day : 'Dia',
    allDayText : 'Todo Dia'
};