package org.prosur.office.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-07-10T10:52:37.829-03:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "IPOfficeWSService", 
                  wsdlLocation = "http://localhost:8080/IpofficeServices/services/IPOfficeWSPort?wsdl",
                  targetNamespace = "http://ws.office.prosur.org/") 
public class IPOfficeWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.office.prosur.org/", "IPOfficeWSService");
    public final static QName IPOfficeWSPort = new QName("http://ws.office.prosur.org/", "IPOfficeWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/IpofficeServices/services/IPOfficeWSPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IPOfficeWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/IpofficeServices/services/IPOfficeWSPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IPOfficeWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IPOfficeWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IPOfficeWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IPOfficeWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IPOfficeWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IPOfficeWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IPOfficeWS
     */
    @WebEndpoint(name = "IPOfficeWSPort")
    public IPOfficeWS getIPOfficeWSPort() {
        return super.getPort(IPOfficeWSPort, IPOfficeWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPOfficeWS
     */
    @WebEndpoint(name = "IPOfficeWSPort")
    public IPOfficeWS getIPOfficeWSPort(WebServiceFeature... features) {
        return super.getPort(IPOfficeWSPort, IPOfficeWS.class, features);
    }

}
