package org.prosur.office.ws;

import javax.ejb.EJB;
import javax.ejb.Stateless;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.gov.inpi.services.ServiceIPOfficeInterface;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-07-10T10:52:37.813-03:00
 * Generated source version: 2.4.6
 * @WebService(targetNamespace = "http://ws.office.prosur.org/", name = "IPOfficeWS")
 */

@Stateless
@WebService()
@XmlSeeAlso({ObjectFactory.class})
public class IPOfficeWS {
	
	@EJB
	ServiceIPOfficeInterface service;

    @WebResult(name = "fileData", targetNamespace = "")
    @RequestWrapper(localName = "getIPRecordFile", targetNamespace = "http://ws.office.prosur.org/", className = "org.prosur.office.ws.GetIPRecordFile")
    @WebMethod
    @ResponseWrapper(localName = "getIPRecordFileResponse", targetNamespace = "http://ws.office.prosur.org/", className = "org.prosur.office.ws.GetIPRecordFileResponse")
    public byte[] getIPRecordFile(
        @WebParam(name = "applicationId", targetNamespace = "")
        java.lang.String applicationId,
        @WebParam(name = "fileName", targetNamespace = "")
        java.lang.String fileName,
        @WebParam(name = "patentType", targetNamespace = "")
        java.lang.String patentType
    ){
    	try {
    		
    		
            byte[] fileData = new byte[] {};
            
            fileData = service.searchFile(applicationId, fileName, patentType);
            
            return fileData;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
}
