
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.prosur.office.ws;

import java.util.logging.Logger;

import javax.ejb.Stateless;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-07-10T10:52:37.735-03:00
 * Generated source version: 2.4.6
 * 
 */

/*@javax.jws.WebService(
                      serviceName = "IPOfficeWSService",
                      portName = "IPOfficeWSPort",
                      targetNamespace = "http://ws.office.prosur.org/",
                      wsdlLocation = "http://localhost:8080/IpofficeServices/services/IPOfficeWSPort?wsdl",
                      endpointInterface = "org.prosur.office.ws.IPOfficeWS")*/

public class IPOfficeWSImpl {

    private static final Logger LOG = Logger.getLogger(IPOfficeWSImpl.class.getName());

    /* (non-Javadoc)
     * @see org.prosur.office.ws.IPOfficeWS#getIPRecordFile(java.lang.String  applicationId ,)java.lang.String  fileName ,)java.lang.String  patentType )*
     */
    public byte[] getIPRecordFile(java.lang.String applicationId,java.lang.String fileName,java.lang.String patentType) { 
        LOG.info("Executing operation getIPRecordFile");
        System.out.println(applicationId);
        System.out.println(fileName);
        System.out.println(patentType);
        try {
            byte[] _return = new byte[] {};
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
